In [136]:
# Show trees with 'status' == 'Alive'
# Replace 'NaN' in spc_latin with '(Unknown)'
# Get 25% of 'tree_dbh' for each 'spc_latin' and apply them to values smaller than 25% 
# Get 75% of 'tree_dbh' for each 'spc_latin' and apply them to values bigger than 75%
# The following columns are requires: 'tree_id', 'tree_dbh', 'stump_diam', 'curb_loc', 'status', 'health', 'spc_latin', 'steward'
# Merge the list of 'Alive' trees with 'describe' stats of grouped alive tree lists by 'spc_latin' with the values of '25%' and '75%'

In [137]:
import pandas as pd

In [138]:
tree_census = pd.read_csv('2015_Street_Tree_Census_-_Tree_Data_20250109.csv')
tree_census

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,boro_ct,state,latitude,longitude,x_sp,y_sp,council district,census tract,bin,bbl
0,180683,348711,08/27/2015,3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,4073900,New York,40.723092,-73.844215,1.027431e+06,202756.7687,29.0,739.0,4052307.0,4.022210e+09
1,200540,315986,09/03/2015,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,...,4097300,New York,40.794111,-73.818679,1.034456e+06,228644.8374,19.0,973.0,4101931.0,4.044750e+09
2,204026,218365,09/05/2015,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.717581,-73.936608,1.001823e+06,200716.8913,34.0,449.0,3338310.0,3.028870e+09
3,204337,217969,09/05/2015,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,3044900,New York,40.713537,-73.934456,1.002420e+06,199244.2531,34.0,449.0,3338342.0,3.029250e+09
4,189565,223043,08/30/2015,21,0,OnCurb,Alive,Good,Tilia americana,American linden,...,3016500,New York,40.666778,-73.975979,9.909138e+05,182202.4260,39.0,165.0,3025654.0,3.010850e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683783,155433,217978,08/18/2015,25,0,OnCurb,Alive,Good,Quercus palustris,pin oak,...,3051900,New York,40.713211,-73.954944,9.967407e+05,199121.6363,34.0,519.0,3062513.0,3.023690e+09
683784,183795,348185,08/29/2015,7,0,OnCurb,Alive,Good,Cladrastis kentukea,Kentucky yellowwood,...,4070700,New York,40.715194,-73.856650,1.023989e+06,199873.6475,29.0,707.0,4075448.0,4.031810e+09
683785,166161,401670,08/22/2015,12,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,5020100,New York,40.620762,-74.136517,9.463514e+05,165466.0763,50.0,201.0,5011657.0,5.004080e+09
683786,184028,504204,08/29/2015,9,0,OnCurb,Alive,Good,Acer rubrum,red maple,...,2023502,New York,40.850828,-73.903115,1.011054e+06,249271.9507,15.0,23502.0,2007757.0,2.028120e+09
683787,200607,306527,09/03/2015,23,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,4134100,New York,40.732165,-73.787526,1.043136e+06,206095.5383,24.0,1341.0,4153657.0,4.071360e+09

In [139]:
tree_census.columns

Index(['tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam',
       'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward',
       'guards', 'sidewalk', 'user_type', 'problems', 'root_stone',
       'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other',
       'brch_light', 'brch_shoe', 'brch_other', 'address', 'postcode',
       'zip_city', 'community board', 'borocode', 'borough', 'cncldist',
       'st_assem', 'st_senate', 'nta', 'nta_name', 'boro_ct', 'state',
       'latitude', 'longitude', 'x_sp', 'y_sp', 'council district',
       'census tract', 'bin', 'bbl'],
      dtype='object')

In [140]:
tree_census_subset = tree_census[['tree_id', 'tree_dbh', 'stump_diam', 
        'curb_loc', 'status', 'health', 'spc_latin', 'steward']]
tree_census_subset_alive = tree_census_subset[tree_census_subset['status'] == 'Alive']
tree_census_subset_alive

,tree_id,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,steward
0,180683,3,0,OnCurb,Alive,Fair,Acer rubrum,NaN
1,200540,21,0,OnCurb,Alive,Fair,Quercus palustris,NaN
2,204026,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,1or2
3,204337,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,NaN
4,189565,21,0,OnCurb,Alive,Good,Tilia americana,NaN
...,...,...,...,...,...,...,...,...
683783,155433,25,0,OnCurb,Alive,Good,Quercus palustris,NaN
683784,183795,7,0,OnCurb,Alive,Good,Cladrastis kentukea,1or2
683785,166161,12,0,OnCurb,Alive,Good,Acer rubrum,NaN
683786,184028,9,0,OnCurb,Alive,Good,Acer rubrum,NaN
683787,200607,23,0,OnCurb,Alive,Fair,Acer rubrum,NaN

In [141]:
tree_census_subset_alive.isna().sum()

tree_id            0
tree_dbh           0
stump_diam         0
curb_loc           0
status             0
health             1
spc_latin          5
steward       487823
dtype: int64

In [142]:
mask = tree_census_subset_alive['spc_latin'].isna()
tree_census_subset_alive.loc[mask, 'spc_latin'] = tree_census_subset_alive.loc[mask, 'spc_latin'].fillna('(Unknown)')
tree_census_subset_alive.groupby('spc_latin').describe()

                   tree_id                                                    \
                     count           mean            std      min        25%
spc_latin
(Unknown)              5.0  408609.200000  286532.190469  47941.0  150745.00
Acer                7080.0  473760.032486  164789.472498    373.0  401640.00
Acer buergerianum    110.0  395036.818182  179390.324434  60373.0  276777.50
Acer campestre      2550.0  383840.281176  184855.325418    214.0  265393.25
Acer ginnala        2049.0  370801.015129  184408.353698   1789.0  244993.00
...                    ...            ...            ...      ...        ...
Tsuga canadensis      88.0  268551.181818  180119.744951  16887.0  145061.75
Ulmus americana     7975.0  308680.330533  206913.335265    123.0  120745.50
Ulmus parvifolia    5345.0  303458.441347  188585.417734    113.0  145469.00
Ulmus pumila        1595.0  318869.944828  203420.294281    305.0  130366.50
Zelkova serrata    29258.0  345718.008989  210287.523422     29.0  158536.25

                                                 tree_dbh             ...  \
                        50%        75%       max    count       mean  ...
spc_latin                                                             ...
(Unknown)          562532.0  630814.00  651014.0      5.0  12.600000  ...
Acer               510781.5  585922.50  721496.0   7080.0  11.675424  ...
Acer buergerianum  386917.0  517254.75  720476.0    110.0   8.090909  ...
Acer campestre     383198.0  515045.25  720857.0   2550.0   7.126275  ...
Acer ginnala       378834.0  501142.00  722311.0   2049.0   7.869204  ...
...                     ...        ...       ...      ...        ...  ...
Tsuga canadensis   220189.5  386305.75  720355.0     88.0   5.193182  ...
Ulmus americana    299464.0  469845.50  722458.0   7975.0  11.953229  ...
Ulmus parvifolia   281187.0  456651.00  721823.0   5345.0   7.417587  ...
Ulmus pumila       333120.0  477250.50  721611.0   1595.0  11.475862  ...
Zelkova serrata    340825.5  519501.75  722683.0  29258.0   7.863559  ...

                               stump_diam
                    75%    max      count mean  std  min  25%  50%  75%  max
spc_latin
(Unknown)          11.0   40.0        5.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Acer               15.0   59.0     7080.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Acer buergerianum  10.0   28.0      110.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Acer campestre      9.0   64.0     2550.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Acer ginnala       10.0   40.0     2049.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...                 ...    ...        ...  ...  ...  ...  ...  ...  ...  ...
Tsuga canadensis    7.0   21.0       88.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Ulmus americana    17.0   65.0     7975.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Ulmus parvifolia   10.0  118.0     5345.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Ulmus pumila       17.0  149.0     1595.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
Zelkova serrata    11.0  210.0    29258.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[133 rows x 24 columns]

In [143]:
stats_alive = tree_census_subset_alive.groupby('spc_latin')['tree_dbh'].describe().reset_index()[['spc_latin','25%','75%']]
stats_alive

             spc_latin  25%   75%
0            (Unknown)  4.0  11.0
1                 Acer  7.0  15.0
2    Acer buergerianum  5.0  10.0
3       Acer campestre  4.0   9.0
4         Acer ginnala  4.0  10.0
..                 ...  ...   ...
128   Tsuga canadensis  2.0   7.0
129    Ulmus americana  4.0  17.0
130   Ulmus parvifolia  3.0  10.0
131       Ulmus pumila  4.0  17.0
132    Zelkova serrata  4.0  11.0

[133 rows x 3 columns]

In [154]:
merged_tree_census_subset_alive = tree_census_subset_alive.merge(stats_alive, on='spc_latin', how='left')
merged_tree_census_subset_alive

,tree_id,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,steward,25%,75%
0,180683,3,0,OnCurb,Alive,Fair,Acer rubrum,NaN,5.0,14.0
1,200540,21,0,OnCurb,Alive,Fair,Quercus palustris,NaN,8.0,24.0
2,204026,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,1or2,6.0,13.0
3,204337,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,NaN,6.0,13.0
4,189565,21,0,OnCurb,Alive,Good,Tilia americana,NaN,4.0,12.0
...,...,...,...,...,...,...,...,...,...,...
652168,155433,25,0,OnCurb,Alive,Good,Quercus palustris,NaN,8.0,24.0
652169,183795,7,0,OnCurb,Alive,Good,Cladrastis kentukea,1or2,3.0,5.0
652170,166161,12,0,OnCurb,Alive,Good,Acer rubrum,NaN,5.0,14.0
652171,184028,9,0,OnCurb,Alive,Good,Acer rubrum,NaN,5.0,14.0
652172,200607,23,0,OnCurb,Alive,Fair,Acer rubrum,NaN,5.0,14.0

In [147]:
mask = merged_tree_census_subset_alive['tree_dbh'] < merged_tree_census_subset_alive['25%']
merged_tree_census_subset_alive.loc[mask, 'tree_dbh'] = merged_tree_census_subset_alive['25%']

mask = merged_tree_census_subset_alive['tree_dbh'] > merged_tree_census_subset_alive['75%']
merged_tree_census_subset_alive.loc[mask, 'tree_dbh'] = merged_tree_census_subset_alive['75%']

merged_tree_census_subset_alive

,tree_id,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,steward,25%,75%
0,180683,5.0,0,OnCurb,Alive,Fair,Acer rubrum,NaN,5.0,14.0
1,200540,21.0,0,OnCurb,Alive,Fair,Quercus palustris,NaN,8.0,24.0
2,204026,6.0,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,1or2,6.0,13.0
3,204337,10.0,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,NaN,6.0,13.0
4,189565,12.0,0,OnCurb,Alive,Good,Tilia americana,NaN,4.0,12.0
...,...,...,...,...,...,...,...,...,...,...
652168,155433,24.0,0,OnCurb,Alive,Good,Quercus palustris,NaN,8.0,24.0
652169,183795,5.0,0,OnCurb,Alive,Good,Cladrastis kentukea,1or2,3.0,5.0
652170,166161,12.0,0,OnCurb,Alive,Good,Acer rubrum,NaN,5.0,14.0
652171,184028,9.0,0,OnCurb,Alive,Good,Acer rubrum,NaN,5.0,14.0
652172,200607,14.0,0,OnCurb,Alive,Fair,Acer rubrum,NaN,5.0,14.0